repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.64.1
    hooks:
      - id: terraform_tflint
      - id: terraform_fmt
      - id: terraform_docs
        args:
          - --hook-config=--path-to-file=README.md
          - --hook-config=--add-to-existing-file=true
          - --hook-config=--create-file-if-not-exist=true
          - --hook-config=--create-file-if-not-exist=true
          - '--args=--hide providers,data-sources,modules,resources,outputs --sort-by required'
  - repo: https://github.com/ansible-community/ansible-lint.git
    rev: v6.0.2
    hooks:
      - id: ansible-lint
        always_run: false
        files: ^ansible/
        exclude_types: [markdown, shell]
