name: Lint
on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  terraform:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/antonbabenko/pre-commit-terraform:latest

    steps:
    - uses: actions/checkout@v2
      name: Checkout source code
    - name: Terraform ckecks
      run: pre-commit run -a

        #    - name: Run tf tests
        #      uses: addnab/docker-run-action@v3
        #      with:
        #          image: ghcr.io/antonbabenko/pre-commit-terraform:latest
        #          options: -v ${{ github.workspace }}:/lint
        #          run: |
        #            run -a
