name: Lint
on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  linters:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/antonbabenko/pre-commit-terraform:latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout source code
      - name: Terraform checks
        run: |
          pre-commit run -a terraform_tflint
          pre-commit run -a terraform_fmt
          pre-commit run -a terraform_docs
      - name: Run ansible-lint
        uses: ansible-community/ansible-lint-action@main
        with:
          path: "ansible/"
